In [1]:
import pandas as pd
import numpy as np
import random as rd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [2]:
data = pd.read_csv("dados100-final.csv", delimiter=";")
data.head()

usuario_id  cookies_enabled  device_memory  hardware_concurrency  \
0           1            False              8                     2   
1           2            False              4                     4   
2           3            False              8                     2   
3           4             True              4                     2   
4           5             True              2                     6   

               ip languages  local_storage    platform  session_storage  \
0  137.183.95.242     pt-BR           True  Windows 10             True   
1   34.131.211.72     pt-BR           True   Windows 8             True   
2  201.98.244.196     pt-BR           True  Windows 10             True   
3      107.5.15.1     pt-BR           True  Windows 10             True   
4  251.203.64.179     pt-BR          False   Windows 8             True   

            timezone  touch_support  browser browser_version  \
0  America/Sao_Paulo          False   Chrome       95.0.4638   
1  America/Sao_Paulo          False  Firefox       80.0.4170   
2  America/Sao_Paulo          False   Chrome       95.0.4638   
3  America/Sao_Paulo          False     Edge       80.0.4170   
4  America/Sao_Paulo          False  Firefox       80.0.4170   

                           gpu                              hash   score  
0  nvidia evga geforce gtx 970   1gd7abb2e497c9f5a00ff94da5dc9e2  0.5660  
1            amd radeon rx 560     1adl54148eac5h2035mbf91h81e8i  0.0600  
2  nvidia evga geforce gtx 970  e09c80c42fda55f9d992e59ca6b3307d  0.1230  
3            amd radeon rx 560   1gd7abb2e497c9f5a00ff94da5dc9e2  0.7265  
4            amd radeon rx 560   1gd7abb2e497c9f5a00ff94da5dc9e2  0.6250

In [3]:
# factorize – codifica os valores categóricos – árvore de decisão do Python precisa de dados numéricos
data['cookies_enabled'],class_names = pd.factorize(data['cookies_enabled']) # Nao=0; Sim=1
print(class_names)
print(data['cookies_enabled'].unique())

Index([False, True], dtype='object')
[0 1]


In [4]:
data['device_memory'],_ = pd.factorize(data['device_memory']) # Medio=0; Baixo=1; Alto=2
print(data['device_memory'].unique())

[0 1 2 3 4 5]


In [5]:
data['hardware_concurrency'],_ = pd.factorize(data['hardware_concurrency']) # Medio=0; Baixo=1; Alto=2
print(data['hardware_concurrency'].unique())

[0 1 2 3 4 5 6]


In [6]:
data['ip'],_ = pd.factorize(data['ip']) # Medio=0; Baixo=1; Alto=2
print(data['ip'].unique())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]


In [7]:
data['languages'],_ = pd.factorize(data['languages']) # Medio=0; Baixo=1; Alto=2
print(data['languages'].unique())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [8]:
data['local_storage'],_ = pd.factorize(data['local_storage']) # Medio=0; Baixo=1; Alto=2
print(data['local_storage'].unique())

[0 1]


In [9]:
data['platform'],_ = pd.factorize(data['platform']) # Medio=0; Baixo=1; Alto=2
print(data['platform'].unique())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [10]:
data['session_storage'],_ = pd.factorize(data['session_storage']) # Medio=0; Baixo=1; Alto=2
print(data['session_storage'].unique())

[0 1]


In [11]:
data['timezone'],_ = pd.factorize(data['timezone']) # Medio=0; Baixo=1; Alto=2
print(data['timezone'].unique())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]


In [12]:
data['touch_support'],_ = pd.factorize(data['touch_support']) # Medio=0; Baixo=1; Alto=2
print(data['touch_support'].unique())

[0 1]


In [13]:
data['browser'],_ = pd.factorize(data['browser']) # Medio=0; Baixo=1; Alto=2
print(data['browser'].unique())

[0 1 2 3 4 5]


In [14]:
data['browser_version'],_ = pd.factorize(data['browser_version']) # Medio=0; Baixo=1; Alto=2
print(data['browser_version'].unique())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36]


In [15]:
data['gpu'],_ = pd.factorize(data['gpu']) # Medio=0; Baixo=1; Alto=2
print(data['gpu'].unique())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [16]:
data['gpu'],_ = pd.factorize(data['gpu']) # Medio=0; Baixo=1; Alto=2
print(data['gpu'].unique())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [17]:
data['hash'],_ = pd.factorize(data['hash']) # Medio=0; Baixo=1; Alto=2
print(data['hash'].unique())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76]


In [18]:
data['score'],_ = pd.factorize(data['score']) # Medio=0; Baixo=1; Alto=2
print(data['score'].unique())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]


In [23]:
data

usuario_id  cookies_enabled  device_memory  hardware_concurrency  ip  \
0            1                0              0                     0   0   
1            2                0              1                     1   1   
2            3                0              0                     0   2   
3            4                1              1                     0   3   
4            5                1              2                     2   4   
..         ...              ...            ...                   ...  ..   
95          96                0              1                     0  88   
96          97                0              1                     0  88   
97          98                1              5                     1  83   
98          99                0              1                     0  89   
99         100                1              1                     0  89   

    languages  local_storage  platform  session_storage  timezone  \
0           0              0         0                0         0   
1           0              0         1                0         0   
2           0              0         0                0         0   
3           0              0         0                0         0   
4           0              1         1                0         0   
..        ...            ...       ...              ...       ...   
95         10              0         3                0        45   
96         10              0         3                0        45   
97         11              0         3                1        46   
98         11              1         2                1        46   
99         11              0         0                0        47   

    touch_support  browser  browser_version  gpu  hash  score  
0               0        0                0    0     0      0  
1               0        1                1    1     1      1  
2               0        0                0    0     2      2  
3               0        2                1    1     0      3  
4               0        1                1    1     0      4  
..            ...      ...              ...  ...   ...    ...  
95              1        0                3   32    73     86  
96              1        0                3   32    73     87  
97              1        0               19   40    74     88  
98              0        0               20   28    75     88  
99              0        4                1   28    76     89  

[100 rows x 16 columns]

In [24]:
data.to_csv("novaplanilha.csv")

In [ ]:
kmeans = KMeans(n_clusters = 3, init = 'random')
kmeans

In [ ]:
kmeans.fit(data)


In [ ]:
kmeans.cluster_centers_


In [ ]:
kmeans.fit(data)

In [ ]:
kmeans.cluster_centers_

In [ ]:
distance = kmeans.fit_transform(data)
distance

In [ ]:
labels = kmeans.labels_
labels

In [ ]:
kmeans.cluster_centers_

In [ ]:
wcsse = []
maxclusters = 11
for i in range(1, maxclusters):
    kmeans = KMeans(n_clusters = i, init = 'random')
    kmeans.fit(data)
    print (i,kmeans.inertia_)
    wcsse.append(kmeans.inertia_)

In [ ]:
plt.plot(range(1, maxclusters), wcsse)
plt.title('Método de Elbow')
plt.xlabel('Qtd. de Clusters')
plt.grid()
plt.ylabel('WCSSE') # Within Cluster Sum of Squares
plt.show()

In [ ]:
data.sample(1)

In [ ]:
X = data[["hash","ip"]]
#Visualise data points
plt.scatter(X["ip"],X["hash"],c='green')
plt.xlabel('ip')
plt.ylabel('hash')
plt.show()

In [ ]:
# Step 1 and 2 - Choose the number of clusters (k) and select random centroid for each cluster

#number of clusters
K=3

# Select random observation as centroids
Centroids = (X.sample(n=K))
plt.scatter(X["ip"],X["hash"],c='black')
plt.scatter(Centroids["ip"],Centroids["hash"],c='red')
plt.xlabel('ip')
plt.ylabel('hash')
plt.show()

In [ ]:
# Step 3 - Assign all the points to the closest cluster centroid
# Step 4 - Recompute centroids of newly formed clusters
# Step 5 - Repeat step 3 and 4

diff = 1
j=0

while(diff!=0):
    XD=X
    i=1
    for index1,row_c in Centroids.iterrows():
        ED=[]
        for index2,row_d in XD.iterrows():
            d1=(row_c["ip"]-row_d["ip"])**2
            d2=(row_c["hash"]-row_d["hash"])**2
            d=np.sqrt(d1+d2)
            ED.append(d)
        X[i]=ED
        i=i+1

    C=[]
    for index,row in X.iterrows():
        min_dist=row[1]
        pos=1
        for i in range(K):
            if row[i+1] < min_dist:
                min_dist = row[i+1]
                pos=i+1
        C.append(pos)
    X["Cluster"]=C
    Centroids_new = X.groupby(["Cluster"]).mean()[["hash","ip"]]
    if j == 0:
        diff=1
        j=j+1
    else:
        diff = (Centroids_new['hash'] - Centroids['hash']).sum() + (Centroids_new['ip'] - Centroids['ip']).sum()
        print(diff.sum())
    Centroids = X.groupby(["Cluster"]).mean()[["hash","ip"]]

In [ ]:
color=['blue','green','gray']
for k in range(K):
    data=X[X["Cluster"]==k+1]
    plt.scatter(data["ip"],data["hash"],c=color[k])
plt.scatter(Centroids["ip"],Centroids["hash"],c='red')
plt.xlabel('ip')
plt.ylabel('hash')
plt.grid()
plt.show()

In [ ]:
teste = [[115,0,2,2,10,1,1,0,1,5,1,2,10,0,55]]
kmeans.predict(teste)

In [ ]:
X.shape

In [ ]:
X.head(5)

In [ ]:
X